const initialDashboardState = {

  //ENROLMENT STATE
  regionEnrollmentDataNorthBasicLivelihood: '',
  regionEnrollmentDataNorthEnhancedLivelihoodYouthChallengeSupport: '',
  regionEnrollmentDataNorthEnhancedLivelihoodJointSkillGroup: '',
  regionEnrollmentDataNorthEnhancedLivelihoodProductionValueChain: '',
  regionEnrollmentDataNorthEnhancedLivelihoodLesp: '',
  regionEnrollmentDataNorthEnhancedLivelihoodCorporativeDevelopment: '',
  regionEnrollmentDataNorthGraduation: '',
  regionEnrollmentDataCentreBasicLivelihood: '',
  regionEnrollmentDataCentreEnhancedLivelihoodYouthChallengeSupport: '',
  regionEnrollmentDataCentreEnhancedLivelihoodJointSkillGroup: '',
  regionEnrollmentDataCentreEnhancedLivelihoodProductionValueChain: '',
  regionEnrollmentDataCentreEnhancedLivelihoodLesp: '',
  regionEnrollmentDataCentreEnhancedLivelihoodCorporativeDevelopment: '',
  regionEnrollmentDataCentreGraduation: '',
  regionEnrollmentDataSouthBasicLivelihood: '',
  regionEnrollmentDataSouthEnhancedLivelihoodYouthChallengeSupport: '',
  regionEnrollmentDataSouthEnhancedLivelihoodJointSkillGroup: '',
  regionEnrollmentDataSouthEnhancedLivelihoodProductionValueChain: '',
  regionEnrollmentDataSouthEnhancedLivelihoodLesp: '',
  regionEnrollmentDataSouthEnhancedLivelihoodCorporativeDevelopment: '',
  regionEnrollmentDataSouthGraduation: '',

  //CASE MANAGEMENT STATE
  caseManagementDataCasesReceived: '',
  caseManagementDataCasesResolved: '',
  caseManagementDataCasesOutstanding: '',
  caseManagementDataCasesResolutionRate: '',

  //PROGRAMS STATE
  numberOfCohortsBasicLivelihood: '',
  numberOfCohortsEnhancedLivelihoodYouthChallengeSupport: '',
  numberOfCohortsEnhancedLivelihoodProductionValueChain: '',
  numberOfCohortsEnhancedLivelihoodLesp: '',
  numberOfCohortsEnhancedLivelihoodCorporativeDevelopment: '',
  numberOfCohortsGraduation: '',
  householdCompletionRateBasicLivelihood: '',
  householdCompletionRateEnhancedLivelihoodYouthChallengeSupport: '',
  householdCompletionRateEnhancedLivelihoodProductionValueChain: '',
  householdCompletionRateEnhancedLivelihoodLesp: '',
  householdCompletionRateEnhancedLivelihoodCorporativeDevelopment: '',
  householdCompletionRateGraduation: '',
  numberOfTrainingsConductedBasicLivelihood: '',
  numberOfTrainingsConductedEnhancedLivelihoodYouthChallengeSupport: '',
  numberOfTrainingsConductedEnhancedLivelihoodProductionValueChain: '',
  numberOfTrainingsConductedEnhancedLivelihoodLesp: '',
  numberOfTrainingsConductedEnhancedLivelihoodCorporativeDevelopment: '',
  numberOfTrainingsConductedGraduation: '',
  typeOfTrainingsBasicLivelihood: '',
  typeOfTrainingsEnhancedLivelihoodYouthChallengeSupport: '',
  typeOfTrainingsEnhancedLivelihoodProductionValueChain: '',
  typeOfTrainingsEnhancedLivelihoodLesp: '',
  typeOfTrainingsEnhancedLivelihoodCorporativeDevelopment: '',
  typeOfTrainingsGraduation: '',
  numberOfComsipTrainingsConductedBasicLivelihood: '',
  numberOfComsipTrainingsConductedEnhancedLivelihoodYouthChallengeSupport: '',
  numberOfComsipTrainingsConductedEnhancedLivelihoodProductionValueChain: '',
  numberOfComsipTrainingsConductedEnhancedLivelihoodLesp: '',
  numberOfComsipTrainingsConductedEnhancedLivelihoodCorporativeDevelopment: '',
  numberOfComsipTrainingsConductedGraduation: '',

  //HOUSEHOLD STATE
  householdEconomicStatusPoorestHouseholds: '',
  householdEconomicStatusPoorerHouseholds: '',
  householdEconomicStatusPoortHouseholds: '',
  householdEconomicStatusRichtHouseholds: '',
  householdHeadmanshipMaleHeadedHouseholds: '',
  householdHeadmanshipFemaleHeadedHouseholds: '',
  householdHeadmanshipChildHeadedHouseholds: ''  
}

export default initialDashboardState
